apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-build-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-build-binding
subjects:
  - kind: ServiceAccount
    name: jenkins # Name is case sensitive
    namespace: ecosystem
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: jenkins-build-role # must match the name of the Role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: build-to-jenkins
spec:
  podSelector:
    matchLabels:
      dogu.name: jenkins
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ecosystem
        - podSelector:
            matchLabels:
              cloudogu.com/pod-kind: jenkins-build

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jenkins-to-build
spec:
  podSelector:
    matchLabels:
      cloudogu.com/pod-kind: jenkins-build
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ecosystem
        - podSelector:
            matchLabels:
              dogu.name: jenkins