apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: build-to-jenkins
spec:
  podSelector:
    matchLabels:
      dogu.name: jenkins
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ecosystem
        - podSelector:
            matchLabels:
              cloudogu.com/pod-kind: jenkins-build
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jenkins-to-build
spec:
  podSelector:
    matchLabels:
      cloudogu.com/pod-kind: jenkins-build
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ecosystem
        - podSelector:
            matchLabels:
              dogu.name: jenkins